### ISSUE TITLE
Bug: Swiping to home causes visual glitch

### ISSUE THREAD

**Issue by tralce** [ChasKane/gay-toolbar#9]
Hi there! I positively adore this plugin!

I noticed a small visual bug. It happens on iOS but likely other mobile devices that use the "swipe up from bottom to go home" gesture. I have had it happen on my iPhone 15 and iPad mini 6.

# When this happens
If I swipe up from the bottom of the screen -- such as to go to the Home screen, or to switch apps. Naturally, when swiping such a gesture, the finger passes across the toolbar, activating a button. 
# The bug
When I switch back to Obsidian, the button is still activated, and remains stuck like this until I close and reopen the app, or use the "Reload app without saving" command.

![Image](https://github.com/user-attachments/assets/9f01abea-7403-485b-954c-8d205a2821f1)

This isn't the end of the world or anything, but I figured I'd report it, and also show my support for the best Obsidian toolbar plugin ever!

**Comment by ChasKane** [comment]
I'm so glad you like the plugin! I imagine iOS isn't playing nicely with Capacitor/React in this case :( but there's surely a solution. I'll fix this in the next release but in the meantime you could add a setTimeout for yourself in GayButton.tsx to clear the css class controlling the animation after some seconds.

**Comment by tralce** [comment]
Thanks so much! 

As someone rather unfamiliar with web languages I'm not sure what to do with that information, but it doesn't really bother me much at all at any rate. "Mildly annoying" would even be greatly overstating it!

**Comment by ChasKane** [comment]
@tralce the latest update should fix this, lmk! Though, I just realized you don't have the bottom nav bar is missing in your setup so I can't properly test it -- how'd you get rid of it? I'm referring to the row of 5 icons at the bottom which only show up on mobile.

![Image](https://github.com/user-attachments/assets/1de23d7f-04c4-4d52-9df6-5912f216c1fe)

**Comment by tralce** [comment]
I've just tested it on my iPad, and it still happens when I swipe the app away. However, now, I can tap on the circle that pops up to dismiss it, which is progress! This makes it a lot less annoying!

<img width="744" alt="Image" src="https://github.com/user-attachments/assets/2faaa0f2-8090-4956-92d6-ef25dac55970" />

# Hiding the Toolbar
I use the **Minimal** theme, in conjunction with the configuration plugins **Style Settings** and **Minimal Theme Settings** -- I hid the mobile toolbar in **Style Settings** → **Minimal Advanced Settings** → **Disable mobile toolbar**. 

I'm not sure if any other plugins are able to do that; this is the only way I've found so far. **Commander** also has an option in the **Toolbar** section that claims to remove the toolbar if the **Row Count** is set to 0 but it doesn't work for me. 

I actually chose to hide it when I discovered Gay Toolbar, since it does far more than the default toolbar, even with Commander, could ever aspire to!

**Comment by ChasKane** [comment]
fair point haha ^.^ yeah any plugin can remove the toolbar by setting it's `display` CSS value to none (something like document.querySelector(".navbar").style.display = "none"). there are some details about ensuring it doesn't show up again when you hide the keyboard but that's it.

Anyway, I'm working on the swipe-commands feature now so stay tuned -- I've realized I really need it for obsidian to truly feel like home on mobile.

**Comment by ChasKane** [comment]
wait I shouldn't have closed this lol.
If the fix I put in this time didn't fix it then I'm not sure what else I can do. I don't have access to an iphone rn but I'll see if I can get the simulator on my mac working. Anyway I'm glad tapping on the ring gets rid of it now.

**Comment by ChasKane** [comment]
hey @tralce could you update to the latest version and 1 lmk what you think(!!) and 2 lmk if this bug persists? <3

**Comment by ChasKane** [comment]
akk we love apple don't we heheh. thanks a bunch, happy swiping!
